### ISSUE TITLE
`codec="gif"` gives not RGB color

### ISSUE THREAD

**Issue by JiahaoYao** [google/mediapy#2]
Hi mediapy, 
This is an AWESOME tool! One quick question 

When I use the `codec="gif"`, the color is not right;
![image](https://user-images.githubusercontent.com/20907377/111847111-70f56f80-88c5-11eb-9869-29250c5d2330.png)

But if I remove that, the color is back:
![image](https://user-images.githubusercontent.com/20907377/111847131-78b51400-88c5-11eb-8d95-9c1b4234ab3f.png)

Do I miss some parameters in order to have the rgb color? 

Again, thanks for open-sourcing this wonderful tool!

**Comment by hhoppe** [comment]
Hi Jiaho,
[GIF](https://en.wikipedia.org/wiki/GIF) can unfortunately only represent a total of 256 distinct colors, so sometimes it doesn't behave well when there are many unique colors  (maybe due to the antialiasing in your frames?).  But your result does look unusual.  Possibly you could share the example data so we can investigate?  Thanks.

**Comment by JiahaoYao** [comment]
Hi @hhoppe , thanks for your fast reply! Here is the [colab](https://colab.research.google.com/drive/1Bj_2u1slUvyhykkpuici-eI3g7-jlaQr?usp=sharing) to reproduce the results.

**Comment by hhoppe** [comment]
Thanks to the example, I found the problem and a fix; it will be posted in a few days.

**Comment by JiahaoYao** [comment]
Great, thanks @hhoppe !
